var f = new Function();
f.prototype.bla = function() { return 1; };
debug.assert(f.bla(), 1);
var g = new f();
debug.assert(g.bla(), 1);
var two = new Function("return 1 + 1");
debug.assert(two(), 2);
var echo = new Function("a", "return a");
debug.assert(echo(1), 1);
debug.assert(echo("kuku"), "kuku");
var sum = new Function("a", "b", "return a+b");
debug.assert(sum(1, 2), 3);
var sum = new Function("a, b", "return a+b");
debug.assert(sum(1, 2), 3);
var sum = new Function("a, b", "c",  "return a+b+c");
debug.assert(sum(1, 2, 3), 6);
debug.assert_exception(function() { var f = new Function("a, b,", "c"); });
