STAGING=staging.$(HOST_OS)
CONFIG_SRC=scripts/kconfig
export CONFIG=staging.$(HOST_OS)/kconfig
MCONF = $(CONFIG)/mconf
CONF = $(CONFIG)/conf
CONFIG_BUILDDIRS = $(CONFIG) $(CONFIG)/lxdialog

$(CONFIG_BUILDDIRS):
	$(Q)mkdir -p $(CONFIG_BUILDDIRS)

$(MCONF): | $(CONFIG_BUILDDIRS)
	@echo "Building $@"
	$(Q)make -C $(CONFIG_SRC) menuconfig $(if $(Q),> /dev/null)

$(CONF): | $(CONFIG_BUILDDIRS)
	@echo "Building $@"
	$(Q)make -C $(CONFIG_SRC) $(if $(Q),> /dev/null)

menuconfig: build_dir $(MCONF)
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(MCONF) Kconfig

config: build_dir $(CONF)
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(CONF) Kconfig

%_defconfig: build_dir $(CONF)
	@echo "*** Default configuration is based on '$@'"
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(CONF) --defconfig=boards/configs/$@ Kconfig

$(BUILD)/.config:
	$(Q)make menuconfig

-include $(BUILD)/auto.conf.cmd

$(BUILD)/auto.conf: $(CONF) $(BUILD)/.config
	$(Q)KCONFIG_AUTOCONFIG=$(BUILD)/auto.conf \
		KCONFIG_AUTOCONFIG_DEP=$(BUILD)/auto.conf.cmd \
		KCONFIG_TRISTATE=$(BUILD)/tristate.conf \
		KCONFIG_CONFIG=$(BUILD)/.config \
		KCONFIG_AUTOHEADER=$(BUILD)/autoconf.h $(CONF) --silentoldconfig Kconfig

$(BUILD)/autoconf.h: $(BUILD)/auto.conf

.PHONY: staging_dir config menuconfig %_defconfig
