STAGING=staging.$(HOST_OS)
CONFIG_SRC=scripts/config
CONFIG=$(STAGING)/config
MCONF = $(CONFIG)/frontends/mconf/mconf
CONF = $(CONFIG)/frontends/conf/conf

$(CONFIG_SRC)/configure:
	@echo "Creating configure script for kconfig-frontends"
	$(Q)cd $(CONFIG_SRC) ; ./bootstrap

$(CONFIG)/Makefile: $(CONFIG_SRC)/configure
	@echo "Configuring kconfig-frontends"
	$(Q)mkdir -p $(CONFIG)
	$(Q)cd $(CONFIG) ; ../../$(CONFIG_SRC)/configure $(if $(Q),-q)

$(MCONF): $(CONFIG)/Makefile
	@echo "Building $@"
	$(Q)make -C $(STAGING)/config $(if $(Q),> /dev/null)

$(CONF): $(CONFIG)/Makefile
	@echo "Building $@"
	$(Q)make -C $(STAGING)/config $(if $(Q),> /dev/null)

menuconfig: build_dir $(MCONF)
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(MCONF) Kconfig

config: build_dir $(CONF)
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(CONF) Kconfig

%_defconfig: build_dir $(CONF)
	@echo "*** Default configuration is based on '$@'"
	$(Q)KCONFIG_CONFIG=$(BUILD)/.config $(CONF) --defconfig=boards/configs/$@ Kconfig

$(BUILD)/.config:
	$(Q)make menuconfig

-include $(BUILD)/auto.conf.cmd

$(BUILD)/auto.conf: $(CONF) $(BUILD)/.config
	$(Q)KCONFIG_AUTOCONFIG=$(BUILD)/auto.conf \
		KCONFIG_AUTOCONFIG_DEP=$(BUILD)/auto.conf.cmd \
		KCONFIG_TRISTATE=$(BUILD)/tristate.conf \
		KCONFIG_CONFIG=$(BUILD)/.config \
		KCONFIG_AUTOHEADER=$(BUILD)/autoconf.h $(CONF) --silentoldconfig Kconfig

$(BUILD)/autoconf.h: $(BUILD)/auto.conf

.PHONY: config menuconfig %_defconfig
